name: Build TV Flix IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r TVFlix.ipa Payload

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: TVFlix-Unsigned
          path: TVFlix.ipa
